# borrowed from https://github.com/simonw/ca-fires-history/blob/main/.github/workflows/scrape.yml

name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '15 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        mkdir -p gameModes
        cd gameModes
        files=("duos" "turbo" "solos")

        for file in ${files[@]}; do
          curl -A "underlords-learderboards-scraper: github.com/tigger0jk/underlords-learderboards-scraper" "https://underlords.com//leaderboarddata?type=$file" | jq > $file.json
        done
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
